[segmentation]
model = "sam2/hiera_small"
device = "cpu"
checkpoint = "models/sam2_hiera_small.pt"
config_file = "models/sam2_hiera_s.yaml"

[segmentation.params]
pred_iou_thresh = 0.88
stability_score_thresh = 0.95

[inpainting]
device = "cpu"
checkpoint = "models/big-lama.pt"
model_url = "https://github.com/enesmsahin/simple-lama-inpainting/releases/download/v0.1.0/big-lama.pt"
